igreja_dll/projeto/Controllers/Membro_TransferenciaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using business.classes;
using repositorioEF;
using System.IO;
using Microsoft.AspNet.Identity;

namespace projeto.Controllers
{
    [Authorize]
    public class Membro_TransferenciaController : Controller
    {
        private DB db = new DB();

        // GET: Membro_Transferencia
        [AllowAnonymous]
        public ActionResult Index()
        {
            var pessoas = db.membro_transferencia.Include(m => m.Cargo_Lider).Include(m => m.Cargo_Lider_Treinamento).Include(m => m.Cargo_Supervisor).Include(m => m.Cargo_Supervisor_Treinamento).Include(m => m.Celula).Include(m => m.Endereco).Include(m => m.Telefone);
            return View(pessoas.ToList());
        }

        // GET: Membro_Transferencia/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Membro_Transferencia membro_Transferencia = db.membro_transferencia.Find(id);
            if (membro_Transferencia == null)
            {
                return HttpNotFound();
            }
            return PartialView(membro_Transferencia);
        }

        // GET: Membro_Transferencia/Create
        public ActionResult Create()
        {
            ViewBag.email = User.Identity.GetUserName();
            ViewBag.Id = new SelectList(db.lider, "Liderid", "Liderid");
            ViewBag.Id = new SelectList(db.lider_treinamento, "Lidertreinamentoid", "Lidertreinamentoid");
            ViewBag.Id = new SelectList(db.supervisor, "Supervisorid", "Supervisorid");
            ViewBag.Id = new SelectList(db.supervisor_treinamento, "Supervisortreinamentoid", "Supervisortreinamentoid");
            ViewBag.celula_ = new SelectList(db.celula, "Celulaid", "Cel_nome");
            ViewBag.Id = new SelectList(db.endereco, "EnderecoId", "Pais");
            ViewBag.Id = new SelectList(db.telefone, "telefoneid", "Fone");
            return View();
        }

        // POST: Membro_Transferencia/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nome,Data_nascimento,Rg,Cpf,Estado_civil,Sexo_masculino,Sexo_feminino,Falescimento,Status,Email,Falta,celula_,Img,imgtipo,classe,Data_batismo,Desligamento,Nome_cidade_transferencia,Estado_transferencia,Nome_igreja_transferencia,Endereco,Telefone,Chamada")] Membro_Transferencia membro_Transferencia, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        membro_Transferencia.imgtipo = upload.ContentType;

                        using (var reader = new BinaryReader(upload.InputStream))
                        {
                            membro_Transferencia.Img = reader.ReadBytes(upload.ContentLength);
                        }
                    }

                    membro_Transferencia.Chamada.Numero_chamada = db.celula.First(c => c.Celulaid == membro_Transferencia.celula_).Pessoas.Count + 1;
                    membro_Transferencia.classe = "Membro por transferencia";
                    db.membro_transferencia.Add(membro_Transferencia);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                catch (Exception ex)
                {
                    ViewBag.email = User.Identity.GetUserName();
                    ViewBag.error = "Você já foi cadastrado. " + ex.Message;
                    ViewBag.celula_ = new SelectList(db.celula, "Celulaid", "Cel_nome");
                    return View(membro_Transferencia);
                }

            }

            ViewBag.Id = new SelectList(db.lider, "Liderid", "Liderid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.lider_treinamento, "Lidertreinamentoid", "Lidertreinamentoid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.supervisor, "Supervisorid", "Supervisorid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.supervisor_treinamento, "Supervisortreinamentoid", "Supervisortreinamentoid", membro_Transferencia.Id);
            ViewBag.celula_ = new SelectList(db.celula, "Celulaid", "Cel_nome", membro_Transferencia.celula_);
            ViewBag.Id = new SelectList(db.endereco, "EnderecoId", "Pais", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.telefone, "telefoneid", "Fone", membro_Transferencia.Id);
            return View(membro_Transferencia);
        }

        // GET: Membro_Transferencia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Membro_Transferencia membro_Transferencia = db.membro_transferencia.Find(id);
            if (membro_Transferencia == null)
            {
                return HttpNotFound();
            }

            ViewBag.email = User.Identity.GetUserName();
            ViewBag.Id = new SelectList(db.lider, "Liderid", "Liderid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.lider_treinamento, "Lidertreinamentoid", "Lidertreinamentoid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.supervisor, "Supervisorid", "Supervisorid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.supervisor_treinamento, "Supervisortreinamentoid", "Supervisortreinamentoid", membro_Transferencia.Id);
            ViewBag.celula_ = new SelectList(db.celula, "Celulaid", "Cel_nome", membro_Transferencia.celula_);
            ViewBag.Id = new SelectList(db.endereco, "EnderecoId", "Pais", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.telefone, "telefoneid", "Fone", membro_Transferencia.Id);
            return View(membro_Transferencia);
        }

        // POST: Membro_Transferencia/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Data_nascimento,Rg,Cpf,Estado_civil,Sexo_masculino,Sexo_feminino,Falescimento,Status,Email,Falta,celula_,Img,imgtipo,classe,Data_batismo,Desligamento,Nome_cidade_transferencia,Estado_transferencia,Nome_igreja_transferencia,Endereco,Telefone")] Membro_Transferencia membro_Transferencia, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        membro_Transferencia.imgtipo = upload.ContentType;

                        using (var reader = new BinaryReader(upload.InputStream))
                        {
                            membro_Transferencia.Img = reader.ReadBytes(upload.ContentLength);
                        }
                    }

                    membro_Transferencia.classe = "Membro por transferencia";
                    db.Entry(membro_Transferencia.Endereco).State = EntityState.Modified;
                    db.Entry(membro_Transferencia.Telefone).State = EntityState.Modified;
                    db.Entry(membro_Transferencia).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                catch (Exception ex)
                {
                    ViewBag.email = User.Identity.GetUserName();
                    ViewBag.error = "Você já foi cadastrado. " + ex.Message;
                    ViewBag.celula_ = new SelectList(db.celula, "Celulaid", "Cel_nome");
                    return View(membro_Transferencia);
                }

            }
            ViewBag.Id = new SelectList(db.lider, "Liderid", "Liderid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.lider_treinamento, "Lidertreinamentoid", "Lidertreinamentoid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.supervisor, "Supervisorid", "Supervisorid", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.supervisor_treinamento, "Supervisortreinamentoid", "Supervisortreinamentoid", membro_Transferencia.Id);
            ViewBag.celula_ = new SelectList(db.celula, "Celulaid", "Cel_nome", membro_Transferencia.celula_);
            ViewBag.Id = new SelectList(db.endereco, "EnderecoId", "Pais", membro_Transferencia.Id);
            ViewBag.Id = new SelectList(db.telefone, "telefoneid", "Fone", membro_Transferencia.Id);
            return View(membro_Transferencia);
        }

        // GET: Membro_Transferencia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Membro_Transferencia membro_Transferencia = db.membro_transferencia.Find(id);
            if (membro_Transferencia == null)
            {
                return HttpNotFound();
            }
            return View(membro_Transferencia);
        }

        // POST: Membro_Transferencia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Membro_Transferencia membro_Transferencia = db.membro_transferencia.Find(id);

igreja_dll/projeto/Controllers/arquivoController.cs
using business.classes;
using repositorioEF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projeto.Controllers
{
    public class arquivoController : Controller
    {
        private DB db = new DB();
        // GET: arquivo
        public ActionResult Exibir(int id)
        {
            Pessoa pessoa = db.pessoas.Find(id);
            return File(pessoa.Img, pessoa.imgtipo);
        }
    }
}

igreja_dll/projeto/Views/Membro_Transferencia/Delete.cshtml
@model business.classes.Membro_Transferencia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Membro_Transferencia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Celula.Cel_nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celula.Cel_nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Pais)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Pais)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone.Fone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone.Fone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_nascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_nascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado_civil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado_civil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo_masculino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo_masculino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo_feminino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo_feminino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Falescimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Falescimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Falta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Falta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_batismo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_batismo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desligamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desligamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome_cidade_transferencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome_cidade_transferencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado_transferencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado_transferencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome_igreja_transferencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome_igreja_transferencia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

igreja_dll/projeto/Views/Membro_Transferencia/Details.cshtml
@model business.classes.Membro_Transferencia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Membro_Transferencia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Celula.Cel_nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celula.Cel_nome)
        </dd> 

        <dt>
            @Html.DisplayNameFor(model => model.Chamada.Numero_chamada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chamada.Numero_chamada)
        </dd>  

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_nascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_nascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado_civil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado_civil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo_masculino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo_masculino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo_feminino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo_feminino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Falescimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Falescimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Falta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Falta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @{
                if (Model.Img != null)
                {
                    <img class="img-responsive" src="@Url.Action("Exibir", "arquivo", new {id = Model.Id })" width="350" />
                }
                else
                {
                    <img class="img-responsive" src="~/arquivos/semimagem.jpg" width="350" />
                }
            }

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_batismo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_batismo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desligamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desligamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome_cidade_transferencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome_cidade_transferencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado_transferencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado_transferencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome_igreja_transferencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome_igreja_transferencia)
        </dd>         

    </dl>
</div>

<div>
    <h4>Endereço</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Pais)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Pais)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Cep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Cep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Rua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Rua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Numero_casa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Numero_casa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Complemento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Complemento)
        </dd>

    </dl>
</div>

<div>
    <h4>Telefone</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.Telefone.Fone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone.Fone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone.Whatsapp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone.Whatsapp)
        </dd>

    </dl>
</div>

<div>
    <h4>Ministérios</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Ministerios)
        </dt>

        <dd>
            @{
                for (int i = 0; i < Model.Ministerios.Count; i++)
                {
                    var valor = Model.Ministerios[i].Nome;
                    <a href="/Ministerio/Details/@Model.Ministerios[i].ministerioid">@valor</a>
                }
            }
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

igreja_dll/projeto/Views/Membro_Transferencia/Index.cshtml
@model IEnumerable<business.classes.Membro_Transferencia>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                <a href="#" class="btn btn-default details" data-value="@item.Id">Detalhes</a>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Detalhes</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="conteudomodal"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                @*<button type="button" class="btn btn-primary">Save changes</button>*@
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
    $(document).ready(function () {

        $(".details").click(function () {

            var id = $(this).data("value");

            $("#conteudomodal").load("/Membro_transferencia/Details/" + id, function () {
                $('#exampleModalLong').modal("show");

            });
        });
    });
    </script>

}